#!/bin/sh
# File generated by ocamlbuild

cd /home/WhiteWolf/ECC-OCaml/src

rm -f EccPrimitives.cmi
rm -f EccPrimitives.cmo
rm -f EccPrimitives.cmx
rm -f EccPrimitives.o
rm -f Ecdh.cmi
rm -f Ecdh.cmo
rm -f Ecdh.cmx
rm -f Ecdh.o
rm -f Ecdsa.cmi
rm -f Ecdsa.cmo
rm -f Ecdsa.cmx
rm -f Ecdsa.o
rm -f ecc.a
rm -f ecc.cma
rm -f ecc.cmxa
# Also clean the script itself
rm -f /home/WhiteWolf/ECC-OCaml/src/_build/sanitize.sh
